import { Header } from "@/components/common/Header";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>React Assignment Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header>Welcome dear customer</Header>
            </main>
        </>
    );
}
