import { api } from "@/api";
import Head from "next/head";
import { DataGrid } from "@mui/x-data-grid";
import { Typography, Fab } from "@mui/material";
import { Add } from "@mui/icons-material";
import Link from "next/link";

export default function Home({ roles }) {
    return (
        <>
            <Head>
                <title>React Assignment Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Typography sx={{ paddingBottom: 4 }} variant="h6">
                    Roles
                </Typography>
                <DataGrid
                    rows={Object.values(roles)}
                    initialState={{
                        sorting: {
                            sortModel: [{ field: "name", sort: "asc" }],
                        },
                    }}
                    columns={[
                        {
                            field: "id",
                            headerName: "ID",
                        },
                        {
                            field: "name",
                            headerName: "Role",
                        },
                        {
                            field: "description",
                            headerName: "Description",
                            width: 500,
                        },
                    ]}
                />

                <Link href="/roles/create">
                    <Fab sx={{ position: "fixed", right: 16, bottom: 16 }} color="primary">
                        <Add />
                    </Fab>
                </Link>
            </main>
        </>
    );
}

export const getServerSideProps = async (context) => {
    const { data } = await api.get("/roles");
    return { props: { roles: data } };
};
